blank_issues_enabled: false
contact_links:
  - name: "📜 Código de Conduta"
    url: https://github.com/techs-community/.github/blob/main/CODE_OF_CONDUCT.md
    about: "Antes de participar, dá uma olhada nas regras de convivência da comunidade."
